//
//  WordManager.swift
//  TurboType
//
//  Created by Robin jakobsson on 2025-03-25.
//
//hej

import Foundation

class WordManager {
    
    static let shared = WordManager()
    
    private(set) var words : [Word] = [
        Word(word: "Apple", answer: "Äpple"),
        Word(word: "Banana", answer: "Banan"),
        Word(word: "Kiwi", answer: "Kiwi"),
        Word(word: "Car", answer: "Bil"),
        Word(word: "Mouse", answer: "Mus"),
        Word(word: "Orange", answer: "Apelsin"),
        Word(word: "Strawberry", answer: "Jordgubbe"),
        Word(word: "Pineapple", answer: "Ananas"),
        Word(word: "Grapes", answer: "Druvor"),
        Word(word: "Watermelon", answer: "Vattenmelon"),
        Word(word: "Dog", answer: "Hund"),
        Word(word: "Cat", answer: "Katt"),
        Word(word: "Horse", answer: "Häst"),
        Word(word: "Cow", answer: "Ko"),
        Word(word: "Bird", answer: "Fågel"),
        Word(word: "Train", answer: "Tåg"),
        Word(word: "Bicycle", answer: "Cykel"),
        Word(word: "Airplane", answer: "Flygplan"),
        Word(word: "Boat", answer: "Båt"),
        Word(word: "House", answer: "Hus"),
        Word(word: "Door", answer: "Dörr"),
        Word(word: "Window", answer: "Fönster"),
        Word(word: "Table", answer: "Bord"),
        Word(word: "Chair", answer: "Stol"),
        Word(word: "Lamp", answer: "Lampa"),
        Word(word: "Computer", answer: "Dator"),
        Word(word: "Phone", answer: "Telefon"),
        Word(word: "Clock", answer: "Klocka"),
        Word(word: "Sun", answer: "Sol"),
        Word(word: "Moon", answer: "Måne"),
        Word(word: "Star", answer: "Stjärna"),
        Word(word: "Sky", answer: "Himmel"),
        Word(word: "Tree", answer: "Träd"),
        Word(word: "Flower", answer: "Blomma"),
        Word(word: "Grass", answer: "Gräs"),
        Word(word: "Mountain", answer: "Berg"),
        Word(word: "River", answer: "Flod"),
        Word(word: "Lake", answer: "Sjö"),
        Word(word: "Ocean", answer: "Hav"),
        Word(word: "Fish", answer: "Fisk"),
        Word(word: "Bear", answer: "Björn"),
        Word(word: "Wolf", answer: "Varg"),
        Word(word: "Snake", answer: "Orm"),
        Word(word: "Elephant", answer: "Elefant"),
        Word(word: "Lion", answer: "Lejon"),
        Word(word: "Tiger", answer: "Tiger"),
        Word(word: "Monkey", answer: "Apa"),
        Word(word: "Butterfly", answer: "Fjäril"),
        Word(word: "Bee", answer: "Bi"),
        Word(word: "Carrot", answer: "Morot"),
        Word(word: "Potato", answer: "Potatis"),
        Word(word: "Tomato", answer: "Tomat"),
        Word(word: "Cucumber", answer: "Gurka"),
        Word(word: "Onion", answer: "Lök"),
        Word(word: "Milk", answer: "Mjölk"),
        Word(word: "Bread", answer: "Bröd"),
        Word(word: "Cheese", answer: "Ost"),
        Word(word: "Egg", answer: "Ägg"),
        Word(word: "Sugar", answer: "Socker"),
        Word(word: "Salt", answer: "Salt"),
        Word(word: "Pepper", answer: "Peppar"),
        Word(word: "Chocolate", answer: "Choklad"),
        Word(word: "Ice cream", answer: "Glass"),
        Word(word: "Peach", answer: "Persika"),
        Word(word: "Plum", answer: "Plommon"),
        Word(word: "Cherry", answer: "Körsbär"),
        Word(word: "Lemon", answer: "Citron"),
        Word(word: "Pear", answer: "Päron"),
        Word(word: "Blueberry", answer: "Blåbär"),
        Word(word: "Raspberry", answer: "Hallon"),
        Word(word: "Blackberry", answer: "Björnbär"),
        Word(word: "Mango", answer: "Mango"),
        Word(word: "Avocado", answer: "Avokado"),
        Word(word: "Rabbit", answer: "Kanin"),
        Word(word: "Frog", answer: "Groda"),
        Word(word: "Turtle", answer: "Sköldpadda"),
        Word(word: "Fox", answer: "Räv"),
        Word(word: "Deer", answer: "Hjort"),
        Word(word: "Dolphin", answer: "Delfin"),
        Word(word: "Whale", answer: "Val"),
        Word(word: "Shark", answer: "Haj"),
        Word(word: "Octopus", answer: "Bläckfisk"),
        Word(word: "Crab", answer: "Krabba"),
        Word(word: "Bus", answer: "Buss"),
        Word(word: "Truck", answer: "Lastbil"),
        Word(word: "Motorcycle", answer: "Motorcykel"),
        Word(word: "Helicopter", answer: "Helikopter"),
        Word(word: "Submarine", answer: "Ubåt"),
        Word(word: "Roof", answer: "Tak"),
        Word(word: "Wall", answer: "Vägg"),
        Word(word: "Floor", answer: "Golv"),
        Word(word: "Ceiling", answer: "Innertak"),
        Word(word: "Mirror", answer: "Spegel"),
        Word(word: "Shelf", answer: "Hylla"),
        Word(word: "Cupboard", answer: "Skåp"),
        Word(word: "Couch", answer: "Soffa"),
        Word(word: "Bed", answer: "Säng"),
        Word(word: "Pillow", answer: "Kudde"),
        Word(word: "Backpack", answer: "Ryggsäck"),
        Word(word: "Eraser", answer: "Suddgummi"),
        Word(word: "Scissors", answer: "Sax"),
        Word(word: "Marker", answer: "Märkpenna"),
        Word(word: "Sunflower", answer: "Solros"),
        Word(word: "Rose", answer: "Ros"),
        Word(word: "Lily", answer: "Lilja"),
        Word(word: "Tulip", answer: "Tulpan"),
        Word(word: "Daisy", answer: "Prästkrage"),
        Word(word: "Rain", answer: "Regn"),
        Word(word: "Snow", answer: "Snö"),
        Word(word: "Storm", answer: "Storm"),
        Word(word: "Wind", answer: "Vind"),
        Word(word: "Fog", answer: "Dimma"),
        Word(word: "Lightning", answer: "Blixt"),
        Word(word: "Thunder", answer: "Åska"),
        Word(word: "Bread", answer: "Bröd"),
        Word(word: "Rice", answer: "Ris"),
        Word(word: "Pasta", answer: "Pasta"),
        Word(word: "Butter", answer: "Smör"),
        Word(word: "Yogurt", answer: "Yoghurt"),
        Word(word: "Meat", answer: "Kött"),
        Word(word: "Chicken", answer: "Kyckling"),
        Word(word: "Fish", answer: "Fisk"),
        Word(word: "Soup", answer: "Soppa"),
        Word(word: "Salad", answer: "Sallad"),
    ]
}
