//
//  WordManager.swift
//  TurboType
//
//  Created by Robin jakobsson on 2025-03-25.
//
//hej

import Foundation

class WordManager {
    
    static let shared = WordManager()
    
    private(set) var words : [Word] = [
        Word(word: "Apple", answer: "Äpple"),
        Word(word: "Banana", answer: "Banan"),
        Word(word: "Kiwi", answer: "Kiwi"),
        Word(word: "Car", answer: "Bil"),
        Word(word: "Mouse", answer: "Mus"),
        Word(word: "Orange", answer: "Apelsin"),
        Word(word: "Strawberry", answer: "Jordgubbe"),
        Word(word: "Pineapple", answer: "Ananas"),
        Word(word: "Grapes", answer: "Druvor"),
        Word(word: "Watermelon", answer: "Vattenmelon"),
        Word(word: "Dog", answer: "Hund"),
        Word(word: "Cat", answer: "Katt"),
        Word(word: "Horse", answer: "Häst"),
        Word(word: "Cow", answer: "Ko"),
        Word(word: "Bird", answer: "Fågel"),
        Word(word: "Train", answer: "Tåg"),
        Word(word: "Bicycle", answer: "Cykel"),
        Word(word: "Airplane", answer: "Flygplan"),
        Word(word: "Boat", answer: "Båt"),
        Word(word: "House", answer: "Hus"),
        Word(word: "Door", answer: "Dörr"),
        Word(word: "Window", answer: "Fönster"),
        Word(word: "Table", answer: "Bord"),
        Word(word: "Chair", answer: "Stol"),
        Word(word: "Lamp", answer: "Lampa"),
        Word(word: "Computer", answer: "Dator"),
        Word(word: "Phone", answer: "Telefon"),
        Word(word: "Clock", answer: "Klocka"),
        Word(word: "Sun", answer: "Sol"),
        Word(word: "Moon", answer: "Måne"),
        Word(word: "Star", answer: "Stjärna"),
        Word(word: "Sky", answer: "Himmel"),
        Word(word: "Tree", answer: "Träd"),
        Word(word: "Flower", answer: "Blomma"),
        Word(word: "Grass", answer: "Gräs"),
        Word(word: "Mountain", answer: "Berg"),
        Word(word: "River", answer: "Flod"),
        Word(word: "Lake", answer: "Sjö"),
        Word(word: "Ocean", answer: "Hav"),
        Word(word: "Fish", answer: "Fisk"),
        Word(word: "Bear", answer: "Björn"),
        Word(word: "Wolf", answer: "Varg"),
        Word(word: "Snake", answer: "Orm"),
        Word(word: "Elephant", answer: "Elefant"),
        Word(word: "Lion", answer: "Lejon"),
        Word(word: "Tiger", answer: "Tiger"),
        Word(word: "Monkey", answer: "Apa"),
        Word(word: "Butterfly", answer: "Fjäril"),
        Word(word: "Bee", answer: "Bi"),
        Word(word: "Carrot", answer: "Morot"),
        Word(word: "Potato", answer: "Potatis"),
        Word(word: "Tomato", answer: "Tomat"),
        Word(word: "Cucumber", answer: "Gurka"),
        Word(word: "Onion", answer: "Lök"),
        Word(word: "Milk", answer: "Mjölk"),
        Word(word: "Bread", answer: "Bröd"),
        Word(word: "Cheese", answer: "Ost"),
        Word(word: "Egg", answer: "Ägg"),
        Word(word: "Sugar", answer: "Socker"),
        Word(word: "Salt", answer: "Salt"),
        Word(word: "Pepper", answer: "Peppar"),
        Word(word: "Chocolate", answer: "Choklad"),
        Word(word: "Ice cream", answer: "Glass"),
        Word(word: "Knowledge", answer: "Kunskap"),
        Word(word: "Wisdom", answer: "Visdom"),
        Word(word: "Experience", answer: "Erfarenhet"),
        Word(word: "Challenge", answer: "Utmaning"),
        Word(word: "Responsibility", answer: "Ansvar"),
        Word(word: "Achievement", answer: "Prestation"),
        Word(word: "Opportunity", answer: "Möjlighet"),
        Word(word: "Determination", answer: "Beslutsamhet"),
        Word(word: "Perspective", answer: "Perspektiv"),
        Word(word: "Imagination", answer: "Fantasi"),
        Word(word: "Curiosity", answer: "Nyfikenhet"),
        Word(word: "Confidence", answer: "Självförtroende"),
        Word(word: "Independence", answer: "Självständighet"),
        Word(word: "Cooperation", answer: "Samarbete"),
        Word(word: "Innovation", answer: "Innovation"),
        Word(word: "Ambition", answer: "Ambition"),
        Word(word: "Dedication", answer: "Hängivenhet"),
        Word(word: "Perseverance", answer: "Uthållighet"),
        Word(word: "Commitment", answer: "Engagemang"),
        Word(word: "Transformation", answer: "Förvandling"),
        Word(word: "Compassion", answer: "Medkänsla"),
        Word(word: "Empathy", answer: "Empati"),
        Word(word: "Tolerance", answer: "Tolerans"),
        Word(word: "Patience", answer: "Tålamod"),
        Word(word: "Integrity", answer: "Integritet"),
        Word(word: "Humility", answer: "Ödmjukhet"),
        Word(word: "Resilience", answer: "Motståndskraft"),
        Word(word: "Adaptability", answer: "Anpassningsförmåga"),
        Word(word: "Sustainability", answer: "Hållbarhet"),
        Word(word: "Consequence", answer: "Konsekvens"),
        Word(word: "Perspective", answer: "Synvinkel"),
        Word(word: "Interpretation", answer: "Tolkning"),
        Word(word: "Circumstance", answer: "Omständighet"),
        Word(word: "Phenomenon", answer: "Fenomen"),
        Word(word: "Revolution", answer: "Revolution"),
        Word(word: "Perception", answer: "Uppfattning"),
        Word(word: "Manifestation", answer: "Manifestation"),
        Word(word: "Contradiction", answer: "Motsägelse"),
        Word(word: "Sophistication", answer: "Sofistikering"),
        Word(word: "Appreciation", answer: "Uppskattning"),
        Word(word: "Justification", answer: "Rättfärdigande"),
        Word(word: "Clarification", answer: "Förtydligande"),
        Word(word: "Articulation", answer: "Artikulation"),
        Word(word: "Distinction", answer: "Distinktion"),
        Word(word: "Recognition", answer: "Erkännande"),
        Word(word: "Speculation", answer: "Spekulation")
    ]
}
